# Page settings
baseurl = "localhost:1313"
title = "Institut Inzogo Ncaro"
languageCode = "en-us"
theme = "hugo-elate-theme-master"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "jonathan.adiaheno@outlook.com"
  # Navigation
  [params.navigation]
    brand = "Institut Inzogo Ncaro"
    home = "Accueil"
    services = "Objectifs et Moyens"
    about = "Qui sommes-nous?"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "O'Myènès."
    subtitle = 'Promotion de la culture du faisceau linguisitique Myènè:Adyumba, Enenga, Galwa, Mpongwè, Nkomi et Orungu'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "But"
    description = "Promouvoir la diffusion de l’esprit et de la culture des peuples du faisceau linguistique “Myènè“ dans chacune de ses composantes : Adyumba, Enenga, Galwa, Mpongwè, Nkomi et Orungu ;"
    url = "#"
    button = "Contactez-nous"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Moyen"
    description = "La création d’une ou plusieurs écoles dédiées à l’enseignement de la langue Omyènè et à la transmission de sa culture, la publication et la création de supports d'information."
    button = "Aidez-nous"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "L'institut"
    description = "Apolitique et à but non lucratif, il a pour vocation la recherche sur l'Omyènè, ses racines et son développement en matière linguistique, ethnologique, anthropologique.et culturel."
    url = "#"
    button = "Pourquoi nous?"
    icon = "icon-rocket"
    img = "img_10.jpg"



  # Services section
  [params.services]
    enable = true
    title = "Objectifs et Moyens"
    description = "Les actions de sauvegarde, de conservation et de promotion de la langue Omyènè et de la culture qu’elle véhicule."

    [[params.services.item]]
      title = "Objectifs"
      description = "<p>La participation à l’établissement d’une écriture conventionnelle de l’Omyènè,</p> <p>La promotion d’une littérature appropriée </p> <p>L’appui aux artistes traditionnels compétents dans la préservation et la vulgarisation du patrimoine culturel myènè.</p>"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Vision"
      description = "<p>Effectuer des études et des recherches linguistiques sur la langue et la tradition orale myènè ;</p> <p>Entreprendre et assurer l’enseignement et le développement de la langue omyènè ainsi que la diffusion de l’esprit et de la culture des peuples du faisceau linguistique “myènè“ dans chacune de ses composantes : Adyumba, Enenga, Galwa, Mpongwè, Nkomi et Orungu ;</p> <p>Former un corps enseignant apte à accomplir ces objectifs, ainsi que des chercheurs dans les disciplines y afférentes, en tenant compte de l’évolution sociale, culturelle et scientifique du monde contemporain ;</p> <p>Apporter un appui aux écrivains s’intéressant à la culture myènè en vue de créer un réseau de supports susceptibles de garantir la survie de ce patrimoine;</p> <p>Elaborer et préparer l’adoption d’une convention d’écriture de l’Omyènè dans ses variétés, en vue d’aboutir à la création d’une académie myènè.</p>"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Moyens d'actions"
      description = "<p>La création d’une ou plusieurs écoles dédiées à l’enseignement de la langue Omyènè et à la transmission de sa culture ;</p><p>La collecte de fonds à travers des spectacles, galas, tombolas, dons, et autres activités génératrices de revenus, nécessaires à la réalisation de ses objectifs ;</p><p>La publication et la diffusion des supports d'informations destinés à promouvoir l’enseignement de la langue Omyènè et la transmission de la culture qu’elle véhicule ;</p><p>La création et le développement d'un site Web ;</p><p>L'organisation de forums et séminaires sur la richesse de la culture et de la langue Omyènè ;</p>"
      icon = "icon-video2"

      [[params.services.item]]
      title = "Autres"
      description = "<p>Promouvoir la vulgarisation de la langue Omyènè ainsi que la diffusion des oeuvres éditées (productions littéraires, scientifiques, culturelles et artistiques) par toutes sortes de canaux de communication scripturaire, audio et visuels ;</p><p>Recruter des chercheurs dans les disciplines y afférentes, en tenant compte de l’évolution sociale, culturelle et scientifique du monde contemporain ;</p><p>Créer des classes d’apprentissage, du théâtre, des films et bandes dessinées ;</p><p>organiser des conférences, débats, ateliers et séminaires, des stages, des excursions, des voyages, des jeux, des concours, des prix, des expositions et des émissions radio ou télévisées, en rapport avec ses objectifs ;</p><p>Lancer des campagnes d’information et de sensibilisation ;</p><p>Établir des relations de coopération ou partenariat avec les autres instituts et organismes, nationaux et internationaux, publics ou privés, ainsi que les ONG oeuvrant à la réalisation d’objectifs similaires, spécialisés dans la recherche linguistique ou dans l’aide aux peuples autochtones minoritaires, en particulier avec l’UNESCO et la Chaire de la langue Mpongwè de La Sorbonne à Paris, avec le Centre de Linguistique Gabonaise de Libreville, etc. ;</p><p>Établir des relations de tutelle avec l’Administration Gabonaise à travers les ministères en charge notamment de l’Education nationale, de l’Enseignement supérieur et de la Culture ;</p>"
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Qui sommes-nous?"
    description = "Le Bureau de l’Assemblée Générale Constitutive, sur proposition des Fondateurs, est constitué ainsi qu’il suit :"

    [[params.about.item]]
      name = "Eugénie DAMAS TCHEN"
      position = "Présidente de séance"
      description = ""
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Patrick MBONGUILA"
      position = "Vice-président"
      description = ""
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Léonce Michel OGANDAGA AGONDJO"
      position = "Scrutateur"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

       [[params.about.item]]
      name = "Bernardin AKAGAH,"
      position = "Secrétaire"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      


  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contactez-nous"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "« Espace Nka’ Ayogo » sis à la Cité Georges Damas Alèka / Awendjè III Boîte Postale : 2326."],
        ["icon-phone", "Bientôt"],
        ["icon-envelope", "jonathan.adiaheno@outlook.com"],
        ["icon-globe", '<a href="http://InzogoNcaro.ga/" target="_blank">InzogoNcaro.ga</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Jonathan Adiaheno. Tous droits réservés.<br>Créé par <a href="http://kaiser-services.com/" target="_blank">Kaiser-Services.com</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
